version: '3.8'

# Override configuration for legacy version support
# Usage: docker-compose -f docker-compose.yml -f docker-compose.legacy.yml up

services:
  relayer-dashboard:
    build:
      context: .
      dockerfile: docker/Dockerfile.legacy
    environment:
      - RELAYER_VERSION=${RELAYER_VERSION:-current}
      - HERMES_BINARY=/usr/local/bin/relayer-selector hermes
      - RLY_BINARY=/usr/local/bin/relayer-selector rly
    volumes:
      # Additional volume for legacy configs
      - ./config/legacy:/home/relayer/legacy-configs:ro