version: '3.8'

services:
  relayer-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"      # Web interface
      - "3000:3000"    # API server
      - "5184:5184"    # Go relayer metrics
      - "5185:5185"    # Hermes REST API
    volumes:
      - ./config/hermes:/home/relayer/.hermes
      - ./config/relayer:/home/relayer/.relayer
      - relayer-data:/home/relayer/data
    environment:
      - API_PORT=3000
      - HERMES_REST_URL=http://localhost:5185
      - AUTH_ENABLED=true
      - JWT_SECRET=${JWT_SECRET:-change-me-in-production}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:8080}
    networks:
      - relayer-network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: relayer_dashboard
      POSTGRES_USER: relayer
      POSTGRES_PASSWORD: ${DB_PASSWORD:-relayer123}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - relayer-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis123}
    volumes:
      - redis-data:/data
    networks:
      - relayer-network
    restart: unless-stopped

volumes:
  relayer-data:
  postgres-data:
  redis-data:

networks:
  relayer-network:
    driver: bridge