version: '3.8'

services:
  # API Backend
  api-backend:
    build:
      context: ./relayer-middleware/api
      dockerfile: Dockerfile
    environment:
      - API_PORT=3000
      - JWT_SECRET=${JWT_SECRET:-change-this-secret}
      - COSMOS_RPC_URL=${COSMOS_RPC_URL}
      - OSMOSIS_RPC_URL=${OSMOSIS_RPC_URL}
      - NEUTRON_RPC_URL=${NEUTRON_RPC_URL}
      - NOBLE_RPC_URL=${NOBLE_RPC_URL}
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - relayooor-net

  # Chainpulse Monitoring
  chainpulse:
    build:
      context: ./monitoring
      dockerfile: Dockerfile
    environment:
      - RPC_USERNAME=${RPC_USERNAME}
      - RPC_PASSWORD=${RPC_PASSWORD}
      - COSMOS_WS_URL=${COSMOS_WS_URL:-wss://cosmos-rpc.polkachu.com/websocket}
      - OSMOSIS_WS_URL=${OSMOSIS_WS_URL:-wss://osmosis-rpc.polkachu.com/websocket}
      - NEUTRON_WS_URL=${NEUTRON_WS_URL:-wss://neutron-rpc.polkachu.com/websocket}
      - NOBLE_WS_URL=${NOBLE_WS_URL:-wss://noble-rpc.polkachu.com/websocket}
    volumes:
      - ./config/chainpulse-selected.toml:/config/chainpulse.toml:ro
      - chainpulse-data:/data
    ports:
      - "3001:3001"  # Metrics endpoint
    restart: unless-stopped
    networks:
      - relayooor-net

  # Frontend Web Application
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=http://localhost:3000
      - VITE_CHAINPULSE_URL=http://localhost:3001
    ports:
      - "80:80"
    depends_on:
      - api-backend
      - chainpulse
    restart: unless-stopped
    networks:
      - relayooor-net

networks:
  relayooor-net:
    driver: bridge

volumes:
  chainpulse-data: