services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.simple
    ports:
      - "8080:80"
      - "3000:3000"
    environment:
      - API_PORT=3000
      - AUTH_ENABLED=false
      - REDIS_PASSWORD=redis123
    networks:
      - dashboard-network

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass redis123
    networks:
      - dashboard-network

networks:
  dashboard-network:
    driver: bridge