app = "relayer-dashboard"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  API_PORT = "3000"
  AUTH_ENABLED = "true"

[[services]]
  http_checks = []
  internal_port = 80
  protocol = "tcp"
  script_checks = []
  
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"
    
  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80
    
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
    
  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[services]]
  internal_port = 3000
  protocol = "tcp"
  
  [[services.ports]]
    port = 3000
    handlers = ["tls", "http"]

[[services]]
  internal_port = 5185
  protocol = "tcp"
  
  [[services.ports]]
    port = 5185
    handlers = ["tls", "http"]

[mounts]
  source = "relayer_data"
  destination = "/home/relayer/data"

[metrics]
  port = 5184
  path = "/relayer/metrics"