version: '3.8'

services:
  chainpulse:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # RPC Authentication (optional)
      - RPC_USERNAME=${RPC_USERNAME}
      - RPC_PASSWORD=${RPC_PASSWORD}
      
      # Chain-specific WebSocket URLs (optional overrides)
      - CHAIN_OSMOSIS_WS=${CHAIN_OSMOSIS_WS:-wss://rpc.osmosis.zone/websocket}
      - CHAIN_COSMOSHUB_WS=${CHAIN_COSMOSHUB_WS:-wss://rpc.cosmos.network/websocket}
      - CHAIN_SEI_WS=${CHAIN_SEI_WS:-wss://sei-rpc.polkachu.com/websocket}
    volumes:
      - ./config:/config:ro
      - chainpulse-data:/data
    ports:
      - "3001:3001"
    restart: unless-stopped
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - monitoring
    depends_on:
      - chainpulse

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning:ro
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - monitoring
    depends_on:
      - prometheus

volumes:
  chainpulse-data:
  prometheus-data:
  grafana-data:

networks:
  monitoring:
    driver: bridge