# Chainpulse configuration for selected chains
# Using Skip endpoints with authentication
# NOTE: Neutron is temporarily excluded due to Slinky oracle vote extensions
# which cause parsing errors in chainpulse

[database]
path = "/data/chainpulse.db"

[metrics]
enabled = true
port = 3001
stuck_packets = true
populate_on_start = true

# Cosmos Hub - Skip endpoint
[chains.cosmoshub-4]
url = "${COSMOS_WS_URL}"
comet_version = "0.37"
username = "${RPC_USERNAME}"
password = "${RPC_PASSWORD}"

# Osmosis - Skip endpoint
[chains.osmosis-1]
url = "${OSMOSIS_WS_URL}"
comet_version = "0.38"
username = "${RPC_USERNAME}"
password = "${RPC_PASSWORD}"

# Noble - Skip endpoint
[chains.noble-1]
url = "${NOBLE_WS_URL}"
comet_version = "0.38"
username = "${RPC_USERNAME}"
password = "${RPC_PASSWORD}"

# Stride - Add as replacement for Neutron
[chains.stride-1]
url = "wss://stride-rpc.lavenderfive.com/websocket"
comet_version = "0.37"
username = "${RPC_USERNAME}"
password = "${RPC_PASSWORD}"