# Chainpulse configuration for Cosmos Hub and Osmosis monitoring

[database]
path = "/data/chainpulse.db"

[metrics]
enabled = true
port = 3001
stuck_packets = true
populate_on_start = true
ibc_handshakes = true

# Cosmos Hub
[chains.cosmoshub-4]
url = "wss://rpc-cosmoshub-ia.cosmosapi.com/websocket"
comet_version = "0.37"
# Authentication will be injected via environment variables
username = "${RPC_USERNAME}"
password = "${RPC_PASSWORD}"

# Osmosis
[chains.osmosis-1]
url = "wss://rpc-osmosis-ia.cosmosapi.com/websocket"
comet_version = "0.37"
# Authentication will be injected via environment variables
username = "${RPC_USERNAME}"
password = "${RPC_PASSWORD}"