global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Chainpulse metrics (when available)
  - job_name: 'chainpulse'
    static_configs:
      - targets: ['host.docker.internal:3001']
    metrics_path: '/metrics'
    scrape_interval: 10s
